include/uapi/linux/bpf.h, include/uapi/linux/if_link.h, src/Makefile, src/bpf.c, src/bpf.h, src/btf.c, src/btf.h, src/libbpf.c, src/libbpf.map
sync with latest bpf-next. tested with fb internal testcase and bcc.
Signed-off-by: Yonghong Song <yhs@fb.com>
=> sync with latest bpf-next

CHECKPOINT-COMMIT, include/uapi/linux/bpf.h, src/btf.c, src/libbpf.c, src/xsk.c
Tested compilation against pahole and internal FB repo.
=> libbpf sync 2019-03-19T04:20:16.365Z

scripts/sync-kernel.sh
Merges are common. `git cherry-pick` can't cherry-pick merge commit and
requires specifying which of the parents should be cherry-picked, so
it's a pain. But merges are also commonly empty, so it's safe to skip them.
This change goes through all merges touching libbpf files, checks that
they don't have any conflict resolution diffs. If there are any, abort,
if not, proceed as usual, ignoring merges.
=> scripts/sync_kernel.sh: skip empty merges, preventing cherry-picking

include/linux/compiler.h
[ upstream commit 6b7a21140fca461c6d8d5c65a3746e7da50a409e ]
Needed a custom backport. I've changed fallbacks so that we can
partially pull in barriers step by step. I've fixed x86 ones and
added corresponding arm64 barriers.
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
=> sync: latest tooling changes from kernel

scripts/sync-kernel.sh
1. There is one commit ("libbpf: fix btf_dedup equivalence check
handling of different kinds"), which was originally committed into bpf
tree and manually synced into libbpf (it was a critical bug fix). Now
that bpf and bpf-next trees were merged, this causes duplicate commits in
libbpf. To address this, check is added to see if libbpf repo has
commit with the same subject and allow to skip it.
2. Just checking by subject is not good enough, as we currently have few
commits with subject "bpf: Sync bpf.h to tools/". So script now will ask
user and continue. This allows for human to double-check if commit
needs to be skipped or not.
3. There is a commit ('bfb35c27c65f bpf: fix whitespace for ENCAP_L2
defines in bpf.h'), which modifies both include/uapi/linux/bpf.h and …
=> sync-kernel.sh: detect synced commits, interactively resolve conflicts

.travis.yml, README, travis-ci/managers/debian.sh, travis-ci/managers/xenial.sh
Follow up of PR https://github.com/libbpf/libbpf/pull/36
Fix bugs pointed by at https://github.com/libbpf/libbpf/pull/36#discussion_r276522335
Show Travis build status at README webpage.
Tested by Travis working on forked `libbpf`: https://travis-ci.org/wat-ze-hex/libbpf
=> Travis CI follow-ups

README.md
After making Github recognize README.md as markdown text,
there are a bunch of formatting problems. They are fixed in this commit.
Singed-off-by: Andrii Nakryiko <andriin@fb.com>
=> Fix up README's markdown formatting

src/btf.c, src/libbpf.c, src/xsk.c
Merging latest bpf tree fixes (so not yet updating COMMIT-CHECKPOINT)
=> Libbpf sync (bpf) 2019-07-29T23:13:41.033Z

src/libbpf.c
1. libbpf_num_possible_cpus multi-threading fix
2. BPF prog's btf_fd fix for old kernels
=> Sync two important fixes from bpf tree

scripts/sync-kernel.sh
Lots of changes, all helping to deal with typical (and not so typical) sync problems.
- Centralizing kernel -> github paths mapping, eliminating possibility of out-of-sync problems (relies on bash 4+ associative arrays).
- Much more strict (and now completely automated) duplicate commits detection. Should deal with "sync bpf.h to tools/" duplicates much better.
- More control over cherry-picking process, ability to continue after failure, once problem is resolved by human manually.
- Hacky but pragmatic resolution of non-libbpf conflicts due to patches touching both libbpf and non-libbpf files.
- Similarly to cherry-picking improvements, add manual control over applying patches to github projection repo, allowing continuation after manual resolution in complicated cases.
- Finally, now we …
=> Major sync script upgrade

scripts/sync-kernel.sh
Fix two issues I've encountered during latest bpf/bpf-next sync.
=> scripts: fix empty cherry-pick handling, fix IGNORE_CONSISTENCY check

README.md
Follow-up to https://github.com/libbpf/libbpf/pull/88 (especially https://github.com/libbpf/libbpf/pull/88#issuecomment-547600163, cc @evverx)
The result looks like this:
=> README: add a LGTM badge

.travis.yml
As ceff1e0363c92b34742e6e88d9506b1eeee39880 reminded me of a similar issue from https://github.com/libbpf/libbpf/pull/98#issuecomment-553873098, let's keep this PR open so it won't get forgotten.
=> travis: build on ppc64le as well

scripts/sync-kernel.sh
Commit signature, used to determine already synced commits, includes a short
stats per each file relevant. Fix this script to include only files that are
actually synced (i.e., exclude Makefile, Build file, etc).
=> sync: fix commit signature determination in sync script

travis-ci/vmtest/configs/INDEX, travis-ci/vmtest/configs/blacklist/BLACKLIST-5.5.0, travis-ci/vmtest/configs/blacklist/BLACKLIST-latest, travis-ci/vmtest/mkrootfs.sh, travis-ci/vmtest/run_selftests.sh
- Update disk image
- Update blacklist
- Run `test_maps` and `test_verifier` in addition to `test_progs`
- Add `mkrootfs.sh` image build script
=> Update disk image

travis-ci/vmtest/mkrootfs.sh, travis-ci/vmtest/run_selftests.sh
- Run test_{maps|verifier} only with the latest kernel
- Mount run control script
- Style
Signed-off-by: Julia Kartseva (hex@fb.com)
=> vmtest: libbpf#137 follow-ups

README.md
Add list of Linux distributions with kernel BTF built-in.
Give few useful links to BPF CO-RE-related material to help users get started.
=> README: add BTF and CO-RE info

README.md
We keep getting more and more questions about BPF/libbpf usage.
This repo is not the right place to ask them, as not that many people
monitor it. Re-route folks to bpf@vger.kernel.org
=> README: info on routing general BPF/libbpf quesions

scripts/sync-kernel.sh
Few recurring issues are fixed.
1. When there are patches in bpf tree that hasn't been synced yet, but bpf was
already merged into bpf-next, merged patches would be applied twice,
causing failures, requiring manual resolution. Now this is handled smarter
and shouldn't happen.
2. When synced libbpf repo contains fixes from bpf that weren't yet merged
into bpf-next, those bpf tree changes would cause inconsistency against
bpf-next tree state. That's expected and usually is pretty easy for human
to discard during consistency check, but is hard for automation. So instead
of failing at the very end, ask human whether discrepancies look good.
3. If sync script detected no new patches needed syncing, it previously didn't
restore linux repo state back. Fixed.
Signed-off-by: Andrii Nakryiko …
=> sync: improve sync script to handle common issues

travis-ci/vmtest/configs/blacklist/BLACKLIST-5.5.0, travis-ci/vmtest/configs/blacklist/BLACKLIST-latest
=> vmtests: unblacklist few tests

src/Makefile
Add quiet-by-default mode to Makefile, similar to libbpf Makefile in Linux
repo.
=> makefile: add quiet mode support

README.md, src/Makefile
Also a couple of minor changes for the README.
=> pkgconfig: use literal ${prefix} to allow override

.github/actions/debian/action.yml, .github/actions/setup/action.yml, .github/actions/vmtest/action.yml, .github/workflows/test.yml, travis-ci/managers/debian.sh, travis-ci/vmtest/helpers.sh, travis-ci/vmtest/run.sh
https://github.com/libbpf/libbpf/issues/316
This change supposed to have backward compatibility with travis and with this change i'm expecting that we will run two CIs at the same time.
I would like to get some assistance on coverity - it would be nice if someone can go though https://docs.github.com/en/actions/reference/encrypted-secrets this and set up token
However i can foresee security implications of this - i don't understand what would prevent users from making a PR which would change workflow to print out security token.
=> Duplicate PR CI with github actions

travis-ci/vmtest/run_vmtest.sh
Backport kernel-patches fix for the same issue ([0] and [1]).
[0] https://github.com/kernel-patches/vmtest/commit/17c596fe8b29e37622a0a2c8f6db989723767e3f
[1] https://github.com/kernel-patches/vmtest/commit/a38de685c7b1b700df2f8ebcbabeea6d65970a54
Cc: Sergei Iudin <siudin@fb.com>
=> ci: fix log folding in Github Actions

docs/sphinx/doxygen/Doxyfile
Signed-off-by: Grant Seltzer <grantseltzer@gmail.com>
=> Fix path to Doxygen source code input

travis-ci/vmtest/run.sh
Backport of kernel-patches PR ([0]), done by @thefallentree.
[0] https://github.com/kernel-patches/vmtest/pull/29
=> ci: don't hang on kernel crashes in qemu

scripts/build-fuzzers.sh
Without it coverage reports can't be built
```
[2022-01-31 00:05:36,094 DEBUG] Generating file view html index file as: "/out/report/linux/file_view_index.html".
Traceback (most recent call last):
File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
sys.exit(Main())
File "/opt/code_coverage/coverage_utils.py", line 823, in Main
return _CmdPostProcess(args)
File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
processor.PrepareHtmlReport()
File "/opt/code_coverage/coverage_utils.py", line 577, in PrepareHtmlReport
self.GenerateFileViewHtmlIndexFile(per_file_coverage_summary,
File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
self.GetCoverageHtmlReportPathForFile(file_path),
File "/opt/code_coverage/coverage_utils.py", …
```
=> ci: no longer remove elfutils while building the fuzzer

src/xsk.c
Creating AF_XDP sockets with the XDP_SHARED_UMEM flag set fails when two devices
ifindex (and the queue_id) are the same. This can happen with devices in
different network namespaces.
In the shared UMEM mode, each Xsk is expected to have a dedicated fill and
completion queue. Context data about those queues is stored in a linked-list
within the UMEM object.
The comparison performed to pick the right context for an Xsk prior to calling
bind() only takes into account the ifindex and queue_id of the network device.
However, the ifindex is not a "system-wide" unique identifier, it is unique only
within a network namespace. This results in attributing the same xsk_ctx to
different Xsks.
To fix this, we retrieve the netns_cookie associated with the socket at its
creation and add it in the …
=> libbpf: make shared xsk creation network namespace aware

.github/actions/build-selftests/build_selftests.sh, .github/actions/build-selftests/helpers.sh, travis-ci/vmtest/helpers.sh, travis-ci/vmtest/run_selftests.sh
This pull request proposes the removal/cleanup of a bunch of Travis remnants.
=> Clean up Travis remnants

.github/actions/build-selftests/helpers.sh, .github/workflows/lint.yml, ci/vmtest/helpers.sh, scripts/sync-kernel.sh
=> Shellcheck

README.md, SYNC.md
Explain sync setup expectations, necessary steps, common gotchas and necessary manual adjustments.
=> sync: add sync process documentation at SYNC.md

src/libbpf.c
=> Modify the function name to match the name in the libbpf.map file

.github/actions/build-selftests/action.yml, .github/actions/build-selftests/build_selftests.sh, .github/actions/vmtest/action.yml, .github/workflows/test.yml
* bump llvm default version
* discover ubuntu version at runtime
* force using ubuntu focal runners for s390x
=> ci: preparing ground for Ubuntu 24.04 runners

.github/workflows/cifuzz.yml, .github/workflows/test.yml
=> ci: get rid of s390x kernel tests

include/uapi/linux/stddef.h, scripts/sync-kernel.sh
It contains __struct_group() macro needed for pkt_cls.h UAPI header...
=> sync: sync stddef.h UAPI header
