README, include/uapi/linux/bpf_common.h
bcc still has this file in its src/cc/compat/linux directory.
Add this file to libbpf as well.
Signed-off-by: Yonghong Song <yhs@fb.com>
=> mirror uapi/linux/bpf_common.h file

include/linux/ring_buffer.h
Add fast variant for x86-64 for now, and we can later extend for
others upon demand.
Signed-off-by: Daniel Borkmann <daniel@iogearbox.net>
=> bpf: add ring_buffer.h drop in replacement header

scripts/check-reallocarray.sh
Builds on debian stretch are failing due to:
../scripts/check-reallocarray.sh: 17: ../scripts/check-reallocarray.sh: Syntax error: Bad fd number
Fix the redirect of stdout and stderr.
Signed-off-by: David Ahern <dsahern@gmail.com>
=> Fix redirect in check-reallocarray

include/linux/err.h
Otherwise, we will have the following compilation error:
```
/home/yhs/work/bcc-new/src/cc/libbpf/src/bpf_prog_linfo.c:
In function ‘dissect_jited_func’:
/home/yhs/work/bcc-new/src/cc/libbpf/src/bpf_prog_linfo.c:88:10:
error: ‘EINVAL’ undeclared (first use in this function)
return -EINVAL;
```
The original linux/err.h at linux:tools/include directory
does include "asm/errno.h" as well.
Signed-off-by: Yonghong Song <yhs@fb.com>
=> add asm/errno.h to linux/err.h

src/Makefile
bpf_common.h is hardly ever changed so it was not installed together
with other uapi headers. Some environments are still prefer to be
consistent and install all relevant uapi headers so add bpf_common.h to
uapi headers.
Signed-off-by: Andrey Ignatov <rdna@fb.com>
=> Install bpf_common.h in install_uapi_headers

scripts/sync-kernel.sh
Previous version of script relied on squashing baseline commit and
rebasing rest of commits on top of it. This doesn't work well with git
histories containing merges. This patch changes approach by cherry-picking
commits that have libbpf-related changes and then rewriting history since
last checkpoint.
This still might fail if there were manually resolved merge conflicts for
libbpf, but it's the best we can get as far as I can tell.
Script now also verifies that state of libbpf in Linux's repository exactly
matches the state of libbpf in github repo.
If everything goes smoothing (including verification step), we clean up after
ourselves and only leave libbpf-sync-XXX branch in github's libbpf repo to
push to remote.
=> sync_kernel.sh: revamp sync script to work in the presence of merges

README, scripts/sync-kernel.sh
With xsk.{o,h} changes we started including Linux UAPI's if_xdp.h
header. We need to sync it along the other UAPI headers.
Also updated README to reflect this.
=> scripts: update sync script to do if_xdp.h syncing

src/Makefile
As promised on the LKML, here's the changes to build the pc file in this project too. This PR depends on a new sync from bpf-next that will bring in the libbpf.pc.template file added by commit:
https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/?id=dd399ac9e343c7573c47d6820e4a23013c54749d
And pass CPPFLAGS to the compiler.
=> Build pkg-config file, use CPPFLAGS

README, src/Makefile
When reading this, please consider the point of view of ommon users or distribution packagers, and the most common use cases.
What is good for those use cases:
- default behaviour is the expected behaviour
- use standard commands and tools
- not having to read into makefiles to find out special variables, special flags or special sauces of any kind
- things just work as expected
The expected behaviour is to get out of the box something that works and can be used immediately, which is usually a shared library linked against its dependencies found automatically.
The expected behaviour is also to work seamlessly with existing build systems, toolchains and packaging tools.
In lieu of that view, these 2 commits switch around the makefile behaviour and build the shared lib by default (adding a …
=> build shared library by default and use pkg-config to get libelf flags

src/Makefile
OBJDIR was not specified for libbpf.pc. It works by default since
default value of OBJDIR is current directory, but breaks as soon as
OBJDIR is set to some other directory:
```
% OBJDIR=build DESTDIR=root make install
...
ar rcs build/libbpf.a build/bpf.o build/btf.o build/libbpf.o
build/libbpf_errno.o build/netlink.o build/nlattr.o build/str_error.o
build/libbpf_probes.o build/bpf_prog_linfo.o build/xsk.o
cc -shared  -lelf   build/bpf.o build/btf.o build/libbpf.o build/libbpf_errno.o
build/netlink.o build/nlattr.o build/str_error.o build/libbpf_probes.o
build/bpf_prog_linfo.o build/xsk.o -o build/libbpf.so
make: *** No rule to make target `libbpf.pc', needed by `all'.  Stop.
```
Fix it.
Signed-off-by: Andrey Ignatov <rdna@fb.com>
=> Fix libbpf.pc target

src/Makefile
Bring a number of updates to how DSO is built.
All of them were done earlier in kernel tree, but weren't implemented for the mirror `Makefile`:
* version script for linker;
* version itself;
* symlinks for libbpf.so.<version>;
* SONAME.
See individual patches for details.
=> DSO updates

README, meson.build
Make it possible to include libbpf into projects built by Meson build system as
a subproject. This is the case e.g. for systemd.
meson.build declares dependencies which may be used in parent projects:
`libbpf_static_dep` for static library
`libbpf_shared_dep` for shared library
`bpf_includes` provides the location of bpf.h, btf.h and libbpf.h
Parent projects need to introduce git wrap to build libbpf:
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Wrap-dependency-system-manual.md#wrap-git
An alternative approach is applying a patch with meson.build for libbpf while
building a parent project:
https://github.com/mesonbuild/meson/blob/master/docs/markdown/Wrap-dependency-system-manual.md#wrap-file
Imo it's less transparent and would add more headache.
Note that this commit …
=> add meson.build to integrate libbpf as a subproject of a project built by Meson

.travis.yml, travis-ci/managers/debian.sh, travis-ci/managers/travis_wait.bash, travis-ci/managers/xenial.sh
In order to `libbpf` to be used in systemd some testing is required, see related
discussions in https://github.com/systemd/systemd/pull/12151 and
https://github.com/libbpf/libbpf/pull/29
Having CI will help track issues like https://github.com/libbpf/libbpf/issues/27 and https://github.com/libbpf/libbpf/issues/28
Tests introduced here mirror the tests of systemd:
For Debian: use `docker` virtualization, build with gcc, gcc + asan, clang, clang + asan.
Fror Ubuntu Xenial: build with gcc.
Differences:
For `libbpf` only `libelf` and its dependencies are installed.
Instead of Meson build system `make` is used, so `make` remains the preferred
method of building and `meson.build` doesn't get rooted in `libbpf`.
`travis_wait.bash` is kept as a workaround for …
=> Introduce Travis CI tests

README.md
file rename needed so that github detect it as md file to show
build status
=> README: rename to README.md

include/linux/filter.h
These are used in some of the new commits from bpf-next.
=> filter.h: add missing BPF raw instruction macros

src/Makefile
Signed-off-by: Eelco Chaudron <echaudro@redhat.com>
=> AF_XDP: Fix install_headers to also install AF_XDP ones

include/linux/err.h, src/.gitignore
Add missing PTR_ERR_OR_ZERO implementation. Also add a bunch of
generated files to .gitignore.
=> linux/err.h: add PTR_ERR_OR_ZERO

scripts/sync-kernel.sh
if_xdp.h wasn't added to one of few file lists, causing sync content
verification failure.
=> scripts/sync-kernel.sh: add missing if_xdp.h in one of file lists

scripts/sync-kernel.sh
Fix how non-empty merge detection is done. Allow to proceed despite
non-empty merges (they will typically will cause conflicts during
applying patches, but if conflicts were handled already, it should be ok
to ignore this problem).
Also ensure that diff's output is in unified diff format.
=> sync: fix non-empty merge detection/handling

src/Makefile
Similarly to kernel-side Makefile ([0]), get libbpf version by looking
at latest version in libbpf.map.
[0] https://patchwork.ozlabs.org/patch/1147232/
=> Makefile: get libbpf version from libbpf.map

src/Makefile, travis-ci/managers/debian.sh, travis-ci/managers/xenial.sh
See commit log of second commit for more details. The first commit introduces a check for this bug into Travis CI. You can verify it fails on Debian Testing and Xenial and passes after this commit. Note that there is a pre-existing build failure with ASan+UBSan due to static checker warnings.
=> Fix shared library build with some compilers

src/libbpf.c
When appying urgent fix to Github mirror, before it was pushed to linux
repo, there were some indentation issues, which eventually got fixed
upstream, but are still in Github mirror. Fix it to prevent future merge
conflicts.
=> libbpf: fix Github-only indentation issue

src/.gitignore, src/Makefile
Similarly to Linux's 1bd63524593b ("libbpf: handle symbol versioning properly
for libbpf.a"), add necessary changes to build static and shared object
files separately with extra shared library flags. This allows to
properly handle symbol versioning in shared library mode, while still
having statically linkable library.
Cc: Yonghong Song <yhs@fb.com>
=> makefile: support libbpf symbol versioning in shared library mode

.travis.yml, travis-ci/managers/xenial.sh
As Travis now [supports](https://docs.travis-ci.com/user/multi-cpu-architectures) aarch64 along with x86_64, let's make use of it, in light of the recent aarch64-related issues. This could be, theoretically, extended to other jobs, as you can run a Docker container in LXD, but not the privileged one (which shouldn't be an issue for libbpf, as it is in [systemd](https://github.com/systemd/systemd/pull/13785#issuecomment-544485154)).
=> travis: add an aarch64 Xenial job

.lgtm.yml
This PR fixes the LGTM analysis.
As this project uses only Makefile, without any configuration step, and due to a "non-standard" location of the source files, LGTM kept failing to find the respective Makefile and build the sources. By tricking LGTM's build system auto detection, that we use automake/configure, it correctly sets the source dir, thus the compilation, extraction & analysis steps now work in the `src/` subdirectory, as expected.
~~The `CFLAGS=-Wno-stringop-overflow` workaround should stay there only until #87 is resolved.~~
As mentioned in the comment below, I played around with the LGTM configuration in a separate repository, so you can see it in action before merging this PR:
- LGTM results: https://lgtm.com/projects/g/mrc0mmand/libbpf-lgtm-test/
- PR comments: …
=> lgtm: fix the extraction process

.travis.yml, README.md, scripts/coverity.sh
Let's automate Coverity builds as well, to improve code quality. 
As the build frequency is rate limited, the Coverity runs are limited to the master branch only - that means someone with appropriate privileges has to setup a Travis CI cron job, which would run Travis once per day on the master branch, to get the optimal results.
~~Marking as WIP for now, as I've never used the Travis CI `coverity_scan` addon before, so I'd like to make sure it works as expected.~~ It appears that the `coverity_scan` addon is not as versatile as I'd like it to be, so let's fall back to the *manual* method I'm familiar with.
=> travis: automate Coverity builds

.travis.yml
Follow-up fix for #92 - even though `sudo` is *enabled*, it's not used implicitly during builds.
=> travis: use sudo during the 'install' phase

scripts/coverity.sh
On Ubuntu `/bin/sh` is a symlink to `/bin/dash`, which doesn't support
certain builtins used by the Coverity script (namely pushd/popd)
---
Hopefully a last follow-up for the Coverity-related stuff.
=> coverity: explicitly use bash instead of sh

.travis.yml, travis-ci/managers/ubuntu.sh
Travis now supports IBM Z and IBM Power architectures, so let's enable
them in our CI as well.
See: https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z
=> travis: add an s390x job

LICENSE.BSD-2-Clause, LICENSE.LPGL-2.1
Libbpf is dual-licensed under BSD-2-Clause and LGPL-2.1 licenses. Include
their texts in the root of the repo.
Suggestes-by: Toke Høiland-Jørgensen <toke@redhat.com>
=> libbpf: add BSD-2-Clause and LGPL-2.1 licenses

src/Makefile
These were added to the kernel repo, but not in Github. However, they are
useful for browsing the source in Github while prototyping new features and
compiling them into userspace utilities.
Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>
=> Makefile: Add cscope and tags rules

.travis.yml, travis-ci/vmtest/run.sh, travis-ci/vmtest/setup_example.sh
Extend continuous integration tests by adding testing against various kernel
versions.
The code is based on vmtest CI scripts implemented by osandov@
for drgn [1] with the following modifications:
- The downloadables are stored in Amazon S3 cloud indexed in [2]
- `--setup-cmd` command line option is added to vmtest/run.sh so
setup commands run on VM boot can be set in e.g. `.travis.yml`
- Travis build matrix [2] is introduced for VM tests so VM tests are
followed by the existing CI tests. The matrix has `KERNEL` and
`VMTEST_SETUPCMD` dimensions.
- Minor style fixes.
The vmtest extention code is located in travis-ci/vmtest and contains
`run.sh` and `setup_example.sh`
- `run.sh` is responsible for the vmtest workflow: downloading vmlinux
and rootfs image from the cloud, fs mounting, syncing …
=> libbpf: Add VMTEST to CI

.travis.yml
A follow up of [1]
Travis CI stages use default phases when no override provided.
This leads to Coverity scan stage fail due to execuing the default
before_script: phase of VMTEST.
Fix this with an explicit override with empty value.
[1] https://github.com/libbpf/libbpf/pull/108
=> libbpf: fix Coverity scan CI

README.md
- List of current distros having libbpf packaged from GH
- Rationale of having libbpf packaged from GH
- List of package dependencies
=> Update README with Distributions section

.travis.yml
Travis CI seems to be ignoring empty before_script override. Let's make sure
it's a non-empty no-op.
=> travis-ci: make sure before_script override is non-empty

.travis.yml, travis-ci/managers/debian.sh, travis-ci/managers/ubuntu.sh, travis-ci/vmtest/build_pahole.sh, travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/configs/blacklist/BLACKLIST-latest, travis-ci/vmtest/run_vmtest.sh
Clean up Travis CI config, extract multi-step initializations into scripts.
Also, move kernel-building tests to happen last to not block lightweight
Debian and Ubuntu tests.
This PR also adds step to build pahole from latest sources. It also switches to LLVM 11. It also drops 5.5.0-rc6, which was kept only because it was built with pahole 1.16 and had all the latest BTF features. Now LATEST kernel has that, so there is no need for 5.5.0-rc6 anymore.
=> ci: clean up .travis.yaml, build latest pahole

travis-ci/vmtest/configs/blacklist/BLACKLIST-5.5.0, travis-ci/vmtest/configs/blacklist/BLACKLIST-latest, travis-ci/vmtest/run_selftests.sh
Set up loopback to enable more tests:
- bpf_tcp_ca
- cgroup_attach_autodetach
- cgroup_attach_multi
- cgroup_attach_override
- select_reuseport
- sockmap_ktls
Signed-off-by: Julia Kartseva hex@fb.com
=> vmtest: enable more networking kernel selftests

scripts/sync-kernel.sh
Newer git started emitting warning about dangerousness of filter-branch.
Squelch it with FILTER_BRANCH_SQUELCH_WARNING=1 envvar.
=> sync: squelch annoying warning from filter-branch git command

README.md
Arch recently added BTF to their distribution kernels - see
https://bugs.archlinux.org/task/66260
Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>
----
#
=> README: Add BTF and Clang information for Arch Linux

.travis.yml, travis-ci/vmtest/configs/INDEX, travis-ci/vmtest/configs/blacklist/BLACKLIST-4.9.0
Make sure that libbpf sanitizes BTF properly for older kernels.
Add a stage for 4.9.0 kernel in TravisCI.
For now make test failures non-blocking by adding 4.9.0 to `allow_failures`
section.
Blacklist is copy-pasted 5.5.0 kernel blacklist.
=> travis_ci: run tests for 4.9 kernel

travis-ci/vmtest/run_selftests.sh
Add testing of no-alu32 flavor of test_progs.
=> vmtests: test no-alu32 variant of test_progs

scripts/check-reallocarray.sh, src/Makefile
Currently we hardcode "gcc", which means we get a bogus result any time a non-default CC is passed to Make. In fact, it's bogus even when `CC` is not explicitly set, since Make's default is "cc", which isn't necessarily the same as "gcc".
Fix the issue by passing the compiler to use to `check-reallocarray.sh`.
=> check-reallocarray.sh: Use the same compiler Make does

travis-ci/vmtest/run_vmtest.sh
Whatever happened, clang-11 and llvm-11, to which clang/llvm packages resolve,
respectively, are not there anymore. Seems like clang-12/llvm-12 are the
latest now, but for whatever reason clang/llvm don't resolve to them yet.
Hard-code version 12 for now.
=> vmtests: specify v12 of clang/llvm for now

travis-ci/vmtest/checkout_latest_kernel.sh
Attempt to first fetch bpf-next tree from a snapshot, falling back to shallow
clone, and if that is not enough, doing a full bpf-next clone. This should
both improve a speed and (because of full clone fallback) improve test
reliability if libbpf wasn't synced in a while.
=> vmtests: speed up fetching of bpf-next sources

.travis.yml
Do both builds and selftest runs as part of a single build step. This would
allow to complete CI testing faster, as builds will happen in parallel with
"Kernel LATEST + selftests" run.
Also re-enable s390x build.
=> travis-ci: flatten build stages to gain more speed ups

README.md
Update Travis CI status badge to point to travis-ci.com,
now that libbpf was migrated there.
=> README.md: update Travis CI badge link

src/Makefile
Without this we would be missing symbols, as shown e.g. by
ldd -r libbpf.so
=> Makefile: link against zlib

travis-ci/vmtest/configs/INDEX, travis-ci/vmtest/configs/blacklist/BLACKLIST-latest, travis-ci/vmtest/mkrootfs.sh, travis-ci/vmtest/run.sh
1. Update mkrootfs.sh building root fs
- Remove /etc/fstab from root fs and mount each fs type separately in
S10-mount script.
- devtmpfs can be already mounted prior to S10-mount execution so make
it opt-out. This addresses [0].
- set -eux for scripts
2. Add iproute2 to root fs and whitelist sk_assign test. Addresses
[1][2]. Update INDEX file with 2020-09-27 version.
[0] https://github.com/libbpf/libbpf/pull/145#issuecomment-609673493
[1] https://github.com/libbpf/libbpf/pull/144
[2] https://github.com/libbpf/libbpf/pull/145
=> vmtest: update root fs, whitelist sk_assign test

scripts/sync-kernel.sh
Libbpf doesn't rely on libc_compat.h anymore, so ignore it for the purposes of
syncing libbpf sources into Github.
=> sync: ignore libc_compat.h

README.md
Ubuntu 20.10 is now a good version to do BPF + CO-RE development.
=> readme: add Ubuntu mentions

README.md
Only on amd64 and arm64 kernel builds for now, as we had some issues on some less common 32bit architectures. Will update if we change it.
=> README: mention that Debian 11 ships with BTF support

src/Makefile
'cp -p' preserve file ownership, this may leave files owned by the
current in user in /lib .
Signed-off-by: Matteo Croce <mcroce@microsoft.com>
=> install: don't preserve file owner

travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/run_vmtest.sh
Clang 13 became the new nightly version, so switch to it. Also do vmlinux
compilation with a bit more parallelism. And account python-docutils
installation as part of selftests build.
=> vmtest: switch to Clang/LLVM 13

travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/run_vmtest.sh
Clang 13 regressed BPF code generation causing some of BPF selftests to fail.
Until that is mitigated, stick to version 12.
=> vmtests: revert to Clang/LLVM 12 until Clang 13 regression is fixed

travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/run_vmtest.sh
Clang 13 now has the fix for the original regression, time to get back to
using nightly versions.
This reverts commit adaf538bcac57273bbb151915f30642eb3e06831.
=> Revert "vmtests: revert to Clang/LLVM 12 until Clang 13 regression is fixed"

.travis.yml, travis-ci/managers/debian.sh
GCC 8 builds started failing due to missing gcc-8 package. Let's switch to GCC
10 instead.
=> travis-ci: switch from GCC8 to GCC10

src/Makefile
Having -m flag between source and destination breaks install on MacOS, as
reported in [0]. Fix it by moving the flag to the front.
[0] https://github.com/openwrt/openwrt/pull/3959
=> Makefile: fix install flags order

.travis.yml, travis-ci/managers/debian.sh, travis-ci/managers/ubuntu.sh, travis-ci/vmtest/configs/blacklist/BLACKLIST-5.5.0, travis-ci/vmtest/run_vmtest.sh
@anakryiko Seems like adding libguestfs for https://github.com/libbpf/libbpf/pull/204 requires moving to focal, because bionic libguestfs uses bionic qemu-system-s390x, which is too old for the modern s390x kernels (I remember I bumped into it during my first attempt to add s390x to the CI). I've experimented with the focal libguestfs in a separate repo, and it worked there. So I've taken your commit from https://github.com/libbpf/libbpf/pull/235 for this PR (without the pahole part) and added two fixes on top.
=> travis-ci: update to Ubuntu Focal [v2.0]

travis-ci/vmtest/run.sh
S50-run-tests uses -e, which means that it immediately exits on test
failures without writing /exitcode. Fix by temporarily turning -e off.
Another issue is that $? in S50-run-tests is not quoted, which causes
the random value from the host to be taken (in practice always 0), so
fix that as well.
Finally, this fix has a positive side effect - QEMU no longer hangs
when tests fail. This is because rcS (generated by mkrootfs.sh) also
uses -e and immediately exits, if one of the scripts that it calls
fails, without calling S99-poweroff.
Example output after the fix:
```
Summary: 53/184 PASSED, 5 SKIPPED, 1 FAILED
+ exitstatus=1
+ set -e
+ echo 1
+ chmod 644 /exitstatus
+ for path in /etc/rcS.d/S*
+ '[' -x /etc/rcS.d/S99-poweroff ']'
+ /etc/rcS.d/S99-poweroff
travis_fold:start:shutdown …
```
=> vmtest: fix error reporting

travis-ci/managers/debian.sh
=> travis-ci: use default docker from Focal

.travis.yml, travis-ci/managers/ubuntu.sh, travis-ci/vmtest/run_vmtest.sh
Drop explicit libelf-dev install command, as it should be pre-installed by
Travis CI already, according to .travis.yaml.
=> vmtests: libelf-dev should be already installed

travis-ci/managers/debian.sh
Use aptitude to actually see what's wrong with the dependencies.
=> travis: fix libelf-dev build-dep issues by using aptitude instead of apt-get

.github/workflows/coverity.yml, travis-ci/vmtest/run.sh
I've added COVERITY_SCAN_TOKEN and this change should work.
Seems like we have limit for scans and now it fails with:
"Coverity Scan analysis NOT authorized until Wed, 16 Jun 2021 01:04:24 +0000 UTC."
https://github.com/tsipa/libbpf/runs/2833993416?check_suite_focus=true
but previously i've got green builds: https://github.com/tsipa/libbpf/actions/runs/940726229
also removed 
"echo travis_fold:start:shutdown"
which doesn't have an end and it's not clear what is the purpose of this. If you know that it's intentionally put here pls let me know - i'll rework this part.
=> Add coverity workflow

.github/actions/vmtest/action.yml, .github/workflows/ondemand.yml, travis-ci/vmtest/build_pahole.sh, travis-ci/vmtest/checkout_latest_kernel.sh, travis-ci/vmtest/run_vmtest.sh
Make it possible to start a libbpf vmtest with supplied pahole / linux repo/branch.
Cavet: it will always use latest.config for any supplied kernel
=> Add ondemand vmtest workflow

scripts/sync-kernel.sh
Let us sync linux/{pkt_cls.h,pkt_sched.h} to libbpf repo.
Otherwise, on ubuntu 16.04, system headers will be picked up
and this will result in compilation error like:
.../netlink.c:416:23: error: ‘TC_H_CLSACT’ undeclared (first use in this function)
*parent = TC_H_MAKE(TC_H_CLSACT,
^
.../netlink.c:418:9: error: ‘TC_H_MIN_INGRESS’ undeclared (first use in this function)
TC_H_MIN_INGRESS : TC_H_MIN_EGRESS);
^
.../netlink.c:418:28: error: ‘TC_H_MIN_EGRESS’ undeclared (first use in this function)
TC_H_MIN_INGRESS : TC_H_MIN_EGRESS);
^
.../netlink.c: In function ‘__get_tc_info’:
.../netlink.c:522:11: error: ‘TCA_BPF_ID’ undeclared (first use in this function)
if (!tbb[TCA_BPF_ID])
^
Signed-off-by: Yonghong Song <yhs@fb.com>
=> sync uapi headers linux/pkt_cls.h and linux/pkt_sched.h

.github/actions/setup/action.yml
otherwise container may contain stall repo metadata cached
=> Run apt-get update as a first step for GH actions

README.md, src/Makefile
commit a82a66e ("Extend build and add install rules to Makefile") adds
special handling for LIBSUBDIR on x86_64. Expand this to all
architectures with 64 in name which suggests a 32bit variant exists, and
s390x which is 64bit extension od s390.
Fixes: #337
Fixes: a82a66e ("Extend build and add install rules to Makefile")
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
=> Makefile: Default LIBSUBDIR to lib64 on 64bit architectures.

travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/run_vmtest.sh
CI started to fail with missing clang-13 warning. Bump the version to 14.
=> ci: bump nightly Clang/LLVM version to 14

.github/actions/setup/action.yml, .github/workflows/coverity.yml, travis-ci/managers/debian.sh, travis-ci/vmtest/helpers.sh
github action grouping is broken because we were outputting "::endgroup" where
it needs "::endgroup::". This patch also added some additional grouping around
container setup phase, making output easier to read.
=> Fix text grouping issue on github actions

travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/checkout_latest_kernel.sh, travis-ci/vmtest/prepare_selftests.sh
Only keep stderr output in case of errors. Having a multi-thousand-line output
isn't useful and slows down Github Actions' log view UI.
=> ci: make CI build log less verbose

src/Makefile
Makefile needs relo_core object added to objects list to avoid static
linking errors when doing static compilation:
/bin/ld: .../libbpf.a(libbpf.o): in function `bpf_core_apply_relo':
.../libbpf/src/libbpf.c:5134: undefined reference to `bpf_core_apply_relo_insn'
Signed-off-by: Rafael David Tinoco <rafaeldtinoco@gmail.com>
=> makefile: fix missing object for static compilation

travis-ci/managers/debian.sh, travis-ci/managers/test_compile.sh, travis-ci/managers/ubuntu.sh
This patch adds a test step to link a minimal program to libbpf library produced,
making sure that the library works.
=> Add a test step to produce a minimal binary using libbpf.

travis-ci/vmtest/configs/blacklist/BLACKLIST-latest, travis-ci/vmtest/run_selftests.sh
Upstream bpf/bpf-next should be good, so no temporary blocked tests should
remain. Also enable test_maps back. They are still occasionally flaky, but
good to have a bit more visibility into those failures.
=> ci: restore all temporary disabled tests

travis-ci/vmtest/build_selftests.sh, travis-ci/vmtest/prepare_selftests.sh, travis-ci/vmtest/run.sh, travis-ci/vmtest/run_vmtest.sh
This is required to migrate kernel-patches CI to use this code
instead of fork.
The second part of this change is here https://github.com/tsipa/vmtest/commit/400feb961c06f0f7dacff6e8460620bf3fab1e53
as-is it only works to demonstrate that actions and bash code can be re-used between these two projects. The actual implementation is still to be done.
=> Make CI tests compatible with vanilla kernel tree

travis-ci/vmtest/run.sh
This PR adds a call to test_bpftool_synctypes.py to run_selftests.sh. The objective of this script is to make sure that the different parts of bpftool that should be updated on BPF UAPI changes (type lists, help messages, documentation, bash completion) do remain in sync between them, and with the UAPI headers from the kernel. The motivation to have it in the CI is to effectively make sure that new patchsets consistently update all those parts when necessary.
This PR is similar to https://github.com/kernel-patches/vmtest/pull/22.
=> ci: run script to test bpftool types/options sync

src/libbpf.c, src/libbpf.h, src/libbpf_internal.h, src/xsk.c
Cherry-picking three relevant commits with few important fixes. This doesn't advance upstream checkpoints because bpf-next is currently broken in CI due to kernel warning spam in find_vma.
=> Libbpf sync manual

docs/api.rst
This adds the enums in the header files to be displayed on libbpf.readthedocs.org
Follow up question to this - is everything in the headers a public facing API, and everything in c files private? Is that how things are separated?
Signed-off-by: grantseltzer <grantseltzer@gmail.com>
=> Add enum to be displayed in documentation

travis-ci/vmtest/run_selftests.sh
Doing substring matches allows accidental new tests to be enabled,
when they are not supposed to be. E.g., whitelisting "xdp" allows new
"xdpwall" test on 5.5.0, which wasn't supposed to happen.
Cc: Yucong Sun <fallentree@fb.com>
=> ci: use -a/-d with exact string match for black/whitelisting

.github/workflows/pahole.yml
Initial idea was to run it hourly, but when it runs hourly it produce a
lot of useless noise and we had to switch it do daily. When we run it
daily caching make much less sense and only make debugging more complex.
=> Remove caching of pahole test result

travis-ci/vmtest/run.sh
This is the libbpf port of the PR for the kernel CI, at https://github.com/kernel-patches/vmtest/pull/44.
Original PR description says:
> The bpftool checks work as expected when the CI runs, except that they do not set any error status code for the script on error, which means that the failures are lost among the logs and not reported in a clear way to the reviewers.
>
> Let's account for the status of bpftool checks when exiting from run.sh
>
> Let's also create a summary for the different group tests, at the end of the test logs, under the folded sections. This summary may be extended in the future with a more detailed overview of the tests running in the VM.
=> ci: account for bpftool check results, print a summary of all tests

travis-ci/vmtest/helpers.sh, travis-ci/vmtest/run.sh, travis-ci/vmtest/run_selftests.sh, travis-ci/vmtest/run_vmtest.sh
Libbpf port of https://github.com/kernel-patches/vmtest/pull/47
One difference is that we don't write bpftool result to `/exitstatus`, we keep it in a variable instead (I'm not familiar with guestfish and didn't want to bother writing to the file).
=> Split CI results per group of selftests in final summary

travis-ci/vmtest/configs/whitelist/WHITELIST-4.9.0, travis-ci/vmtest/configs/whitelist/WHITELIST-5.5.0
legacy_printk selftests is specially designed to be runnable on old
kernels and validate libbpf's bpf_trace_printk-related macros. Run them
in CI.
=> ci: whitelist legacy_printk tests on 4.9 and 5.5

travis-ci/vmtest/run.sh
The condition for the test is incorrect, we want to add a default exit status if the file is empty. But [[ -s file ]] returns true if the file exists and has a size greater than zero. Let's reverse the condition.
[ Apologies for the silly mistake, previous PR was merged before I had time to check the result of the latest CI run :/ ]
Fixes: #412
=> ci: fix test on `/exitstatus` existence and size

travis-ci/vmtest/s390x-self-hosted-builder/README.md, travis-ci/vmtest/s390x-self-hosted-builder/actions-runner-libbpf.Dockerfile
This is needed for composite actions with conditional steps.
Fixes #416.
Signed-off-by: Ilya Leoshkevich <iii@linux.ibm.com>
=> ci: upgrade s390x runner to v2.285.0

travis-ci/vmtest/configs/config-latest.x86_64
Add necessary kernel config values to make BPF_PROG_TYPE_LIRC_MODE2
programs work.
=> ci: add LIRC kernel config

docs/api.rst
The API doc only exists in the github repo, so opened the PR here instead of the mailing list.
Signed-off-by: grantseltzer <grantseltzer@gmail.com>
=> Add documentation for error checking in API doc

travis-ci/rootfs/mkrootfs_tweak.sh
Given that the rootfs for Arch Linux uses the busybox variant of
mount(8), the `-l` doesn't exist on that binary and gives the following
error msg with version v1.34.1 of busybox when invoking
mkrootfs_arch.sh:
```
...
[    0.781471] random: fast init done
starting pid 72, tty '': '/etc/init.d/rcS'
+ for path in /etc/rcS.d/S*
+ '[' -x /etc/rcS.d/S10-mount ']'
+ /etc/rcS.d/S10-mount
+ /bin/mount proc /proc -t proc
++ /bin/mount -l -t devtmpfs
/bin/mount: unrecognized option: l
...
```
This prevented me from generating a rootfs. This is fixed by removing
the `-l`, as plainly invoking `mount -t devtmpfs` returns the same
output with `mount -l ...` on the non-busybox variant (on Arch Linux, it
comes from the `utils-linux` package). After this change, I was able to
run …
=> travis-ci/rootfs: Fix mount(8) invocation for Arch Linux

include/linux/types.h
This fixes the build in environments such as Alpine Linux (musl).
/cc @yonghong-song per discussion in https://github.com/iovisor/bcc/issues/2338
----
For reference, this was the build error:
```
[...]
cc -I. -I../include -I../include/uapi -DCOMPAT_NEED_REALLOCARRAY -g -O2 -Werror -Wall -c libbpf.c -o libbpf.o
In file included from /usr/include/linux/byteorder/little_endian.h:13,
from /usr/include/asm/byteorder.h:5,
from /usr/include/linux/perf_event.h:20,
from libbpf.c:32:
/usr/include/linux/swab.h:161:8: error: unknown type name '__always_inline'
static __always_inline __u16 __swab16p(const __u16 *p)
^~~~~~~~~~~~~~~
/usr/include/linux/swab.h:161:30: error: expected '=', ',', ';', 'asm' or '__attribute__' before '__swab16p'
static __always_inline __u16 __swab16p(const __u16 *p)
^~~~~~~~~ …
```
=> Support less common environments like Alpine (musl)

travis-ci/rootfs/s390x-self-hosted-builder/README.md, travis-ci/rootfs/s390x-self-hosted-builder/actions-runner-libbpf.Dockerfile
This PR contains a small tweak for using s390x-self-hosted-builder on an Ubuntu host, as well as documentation changes.
In order to test this change, I've disabled the old RHEL-based builder and enabled the new Ubuntu one. If all tests pass, I'll keep it this way.
=> ci: allow using s390x-self-hosted-builder on an Ubuntu host

README.md
Point to libbpf package in Ubuntu Impish, so it doesn't expire soon.
Closes: https://github.com/libbpf/libbpf/issues/451
=> README: update Ubuntu package link

src/Makefile
Ensure that libbpf.pc gets full libbpf's version, including patch
releases. Also add some mechanism to ensure that official released
version (e.g., 0.7.1) and the one recorded in libbpf.map (which never
bumps patch version, so will be 0.7.0) are in sync up to major and minor
versions. This should ensure that major mistakes are captured. We'll
still need to be very careful with zeroing out patch version on minor
version bumps.
Closes: https://github.com/libbpf/libbpf/issues/455
Reported-by: Michel Salim <michel@fb.com>
=> libbpf: fix libbpf.pc generation w.r.t. patch versions

LICENSE.BSD-2-Clause
Seems like 2015 is the year of the first libbpf commit. So use Lorenz's
suggestion and add "(c) 2015 The Libbpf Authors".
Closes: https://github.com/libbpf/libbpf/issues/461
Reported-by: Lorenz Bauer <lmb@cloudflare.com>
=> LICENSE: fix BSD-2-Clause by adding year and authors

src/Makefile
Add usdt.bpf.h to HEADERS so that it can be installed
and included by users.
Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>
=> Makefile: Add usdt.bpf.h to list of HEADERS

scripts/build-fuzzers.sh
* ci: turn off _FORTIFY_SOURCE explicitly
libelf is compiled with _FORTIFY_SOURCE by default and it isn't compatible with MSan. It was borrowed from https://github.com/google/oss-fuzz/pull/7422
* ci: turn on the alignment check
to catch issues like https://github.com/libbpf/libbpf/issues/391
* ci: point elfutils to a commit where a couple bugs are fixed
Fixes
```
./out/bpf-object-fuzzer: Running 1 inputs 1 time(s) each.
Running: CORPUS/036ff286c13e4590646c7ef59435ec642432da8e
elf_begin.c:232:20: runtime error: member access within misaligned address 0x000001655e71 for type 'Elf64_Shdr', which requires 8 byte alignment
0x000001655e71: note: pointer points here
00 00 00  7f 45 4c 46 02 02 01 00  00 00 07 fb 00 1d 00 00  6c 69 63 65 42 fb 00 41  00 57 03 00 20
^
#0 0x574d51 in get_shnum …
```
=> ci: assorted tweaks related to libelf and OSS-Fuzz/CFLite mostly

.readthedocs.yaml
This enables readthedocs to create downloadable files of every documentation version on build. This includes zipped HTML, PDF, and ePUB formats.
After this is merged I will rebuild every version manually. 
https://readthedocs.org/projects/docs/downloads/pdf/stable/
Signed-off-by: grantseltzer <grantseltzer@gmail.com>
=> Enable downloads feature

.readthedocs.yaml
Turns out I read the wrong documentation when I specified 'all' as the format. I also could have tested it on libbpf-test.readthedocs.org, which I did this time around. 
The issue however is that API docs aren't included in this, and i'm not  sure why. I'll look to address that soon.
https://readthedocs.org/projects/libbpf-test/downloads/
(when this is merged, i'll rebuild for every version)
Signed-off-by: grantseltzer <grantseltzer@gmail.com>
=> Fix downloads formats

travis-ci/rootfs/mkrootfs_arch.sh, travis-ci/rootfs/mkrootfs_debian.sh
Add `ethtool` as a dependency to the rootfs image.
Tested by running and building the rootfs images with both
`sudo ./mkrootfs_arch.sh`
and
`sudo ./mkrootfs_debian.sh`
and running in qemu with:
```
wget https://libbpf-ci.s3-us-west-1.amazonaws.com/x86_64/vmlinuz-5.5.0
rootfs_img=rootfs.img kernel_bzimage=vmlinuz-5.5.0
mkdir rootfs
touch rootfs.img
truncate -s 2G rootfs.img
sudo mount -o loop rootfs.img rootfs
cat ~/Downloads/libbpf-vmtest-rootfs-2022.04.25.tar.zst | sudo tar -C rootfs -I zstd -xvf -
sudo install  -m 755 -o root -g root  /dev/stdin rootfs/etc/rcS.d/S50-startup <<'EOF'
ethtool -h
cat /etc/issue
EOF
qemu-system-x86_64 -nodefaults  -display none -serial mon:stdio -enable-kvm -m 4G -drive file="${rootfs_img}",format=raw,index=1,media=disk,if=virtio,cache=none -kernel …
```
=> [rootfs] update rootfs to ship with ethtool

travis-ci/rootfs/mkrootfs_debian.sh
Hi,
This is the fix for https://lore.kernel.org/bpf/CAEf4BzbqfV1FySVu69-am6hz2ykPWXspqyFV8eG_Gapwp0kUqw@mail.gmail.com/.
You can build a new image yourself or take mine from https://github.com/iii-i/libbpf/raw/libbpf-vmtest-rootfs-2022.05.09/travis-ci/rootfs/libbpf-vmtest-rootfs-2022.05.09.tar.zst.
I tested it with `[PATCH bpf-next v3 0/8] bpf: mptcp: Support for mptcp_sock and is_mptcp` using vmtest.sh.
Best regards,
Ilya
=> vmtest: use debian bookworm

travis-ci/vmtest/configs/blacklist/BLACKLIST-latest.s390x
The xdp_syncookie test uses kfunc, and BPF JIT doesn't support kfunc on
s390x.
Signed-off-by: Maxim Mikityanskiy <maximmi@nvidia.com>
=> ci: blacklist xdp_syncookie on s390x

src/Makefile
Hello team,
I'd like to build bpftool and libbpf-bootstrap project for arm64 Linux, but it seems the support is not as well as host build.
I add some changes in makefile to make it. 
This one is the first one since libbpf is submodule of other projects.
Please let me know if this is the correct way to achieve that, thanks.
=> Makefile: add support for cross compilation

.github/actions/build-selftests/build_selftests.sh
Development on LLVM 16 has started and version 15 is no longer available
in the repository we install it from. Bump the version we use
accordingly.
=> ci: Bump LLVM version we use to 16

.github/actions/vmtest/action.yml
So far we have relied on the kernel configuration as checked into the
this repository. However, a suitable configuration is now included in
upstream Linux [0].
With this change we add support for using the configuration from there.
[0] https://lore.kernel.org/bpf/165893461358.29339.11641967418379627671.git-patchwork-notify@kernel.org/T/#m2a97b0ea9ef0ddee7a53bbf7919e3f324b233937
=> Rely on upstream kernel configuration

.github/actions/vmtest/action.yml, .github/workflows/build.yml, .github/workflows/coverity.yml, .github/workflows/ondemand.yml, .github/workflows/pahole.yml, .github/workflows/test.yml
The current version of actions/checkout is v3. That means that v2, which
we currently use, has been superseded. Update the version we use
accordingly.
=> Use checkout action in version v3

travis-ci/vmtest/run_selftests.sh
Back in 2020, we disabled the test_maps selftest with e05f9be4f4be
("vmtests: temporarily disable test_maps"), for reasons not closely
elaborated.
It appears that by now the test is succeeding again, so let's enable it
back.
=> Re-enable test_maps selftest

.github/actions/vmtest/action.yml
The path to the file system image used by our invocation of Qemu is
currently hard coded to `/tmp/root.img`. With
https://github.com/libbpf/ci/commit/da44c0b6ee29ec53776c1303f7ac790b7e337db5
landed we have the option of specifying it explicitly. Let's do just that.
=> Explicitly specify Qemu image path to use

ci/vmtest/run_selftests.sh
This change adjusts the run_selftests.sh script to accept an optional
list of arguments specifying the tests to run. We will make use of it
once we run selftests in parallel.
=> Support running of individual tests

.github/actions/build-selftests/action.yml, .github/actions/vmtest/action.yml, .github/workflows/coverity.yml
As discussed at some earlier point in time, some of the actions/workflow
logic does not use our foldable helpers despite being able to. Switch
them over.
=> Use foldable helpers where applicable

ci/vmtest/run_selftests.sh
As a follow up to 66b788c1a464 ("Factor out test_progs_noalu function")
and taking into account feedback [0], this change renames the
test_progs_noalu function to test_progs_no_alu32, to stay closer to the
name of the binary being invoked.
[0] https://github.com/kernel-patches/vmtest/pull/124#discussion_r953175641
=> Rename test_progs_noalu function to test_progs_no_alu32

README.md
Add auto-selectable libbpf logo for light and dark themes.
Suggested-by: Quentin Monnet <quentin@isovalent.com>
=> README: add dark background logo image

ci/rootfs/s390x-self-hosted-builder/README.md, ci/rootfs/s390x-self-hosted-builder/actions-runner-libbpf.Dockerfile, ci/rootfs/s390x-self-hosted-builder/fs/usr/bin/actions-runner
* use hostname to set the runner name
* updated https://github.com/actions/runner from c2.285.0 to v2.296.0
=> [s390x] support for consistent runner name + action runner update

.github/actions/vmtest/action.yml
Let's make the "kernel-root" explicit when using the `prepare-rootfs`
action, instead of relying on the default, `.kernel`.
=> Explicitly provide kernel-root argument to `prepare-rootfs` action

.github/actions/vmtest/action.yml
With https://github.com/libbpf/ci/pull/36 merged the run-qemu action now
accepts an additional argument, `kernel-root`.
Provide it to the action with the value appropriate for this repository.
=> Provide kernel-root argument to run-qemu action

.github/actions/vmtest/action.yml
With an upcoming change we would like to invoke bpftool checks from the
run-qemu action (https://github.com/libbpf/ci/pull/37). This action
requires two environment variables, `KERNEL` and `REPO_ROOT`, set in order
to function.
Make sure to set them now. Long term we should probably make them
explicit input arguments instead of implicit global state, but there are
many more such instances that we need to clean up.
=> Set KERNEL and REPO_ROOT environment variable for run-qemu action

ci/vmtest/configs/DENYLIST-5.5.0
Commit 693de729d0a2 ("Rename blacklists and whitelists") renamed the
black and white lists but missed the adjustment of a comment,
referencing a file name. Update it accordingly.
=> Fix comment: WHITELIST -> ALLOWLIST

ci/rootfs/s390x-self-hosted-builder/actions-runner-libbpf.Dockerfile
iproute2 and iputils-ping inside the container can be used to implement healthchecks or for troubleshooting.
=> Adding network diag utils into actions-runner-libbpf container

ci/rootfs/s390x-self-hosted-builder/fs/usr/bin/actions-runner
same name.
This is essentially aligning whith what is done in https://github.com/myoung34/docker-github-actions-runner/blob/0f2883e196f6fc1d9b63ee4473d534e387801f0b/entrypoint.sh#L90-L91
The issue at hand did manifest on s390x host when restarting a runner and GH having an existing runner with the same name. The logic was to default to not replace it and the runner would be started with somne defaults, which mean the name would change, and the labels would be lost, making the runner unusable (while still running): https://gist.github.com/chantra/ef0bd3e0c9e35bb82619636acf2f7c98
By replacing the existing runner, we will not get into that state.
=> [s390x][ci] Force replacing workers when a worker already exist with

ci/vmtest/configs/DENYLIST-latest.s390x
The comment associated with the entry is a bit confusing. It stemmed from the test being denylisted on `bpf`, but not `bpf-next` in the past. Regardless, by now said change has propagated to both trees, so we no longer need to carry around this deny list entry here.
=> Remove lru_bug from DENYLIST-latest.s390x

README.md
libbpf is now packaged as part of the core repository, not the extra repository. Fix the current link which gets a 404.
Signed-off-by: David Vernet <void@manifault.com>
=> README: Fix Arch packaging link

README.md
This adds a documentation badge that links to libbpf.readthedocs.org
When rendered on github it will display the status of the docs build
Signed-off-by: Grant Seltzer <grantseltzer@gmail.com>
=> Add documentation badge to README

src/Makefile
Determining the correct library installation path (lib vs. lib64) using uname(1) breaks in cross compilation scenarios where word widths differ between the host and target system.
Instead, source the information from the compilers '-dumpmachine' option (supported by both GCC and Clang).
We call this the "host" architecture, using the same nomenclature as Autotools (--host configure option).
Signed-off-by: Tobias Waldekranz <tobias@waldekranz.com>
=> Makefile: Fix cross-compilation for 32-bit targets

.github/actions/vmtest/action.yml
As of https://github.com/libbpf/ci/pull/67 a bunch of actions honor KBUILD_OUTPUT. Doing so will make it possible to separate source code from build artifacts, which in turn may allow us to support incremental kernel compilation in CI down the line.
Irrespective of these future changes, actions pertaining the kernel build now ask for an additional input defining where to store or expect build artifacts. Provide it.
=> ci: Provide KBUILD_OUTPUT to actions asking for it

scripts/sync-kernel.sh
Use correct Bash syntax to define these two variables as arrays. Drop shellcheck opt-out for unquoted use of array.
=> sync: make LIBBPF_PATHS and LIBBPF_VIEW_PATHS into real array variables

include/uapi/linux/fcntl.h, scripts/sync-kernel.sh
Libbpf relies on F_DUPFD_CLOEXEC constant coming from fcntl.h UAPI header, so we need to sync it along other UAPI headers. Also update sync script to keep doing this automatically going forward.
Reported-by: Arnaldo Carvalho de Melo <acme@redhat.com>
=> sync: start syncing include/uapi/linux/fcntl.h UAPI header

ci/managers/debian.sh
Seems like we need pkgconfig dependency instead of pkg-config.
=> ci: fix Debian builds due to pkg-config dependency change

.github/workflows/build.yml, ci/managers/debian.sh
Add few more versions of clang and gcc used to compile-test libbpf.
=> ci: build libbpf with more versions of clang and gcc

.github/workflows/test.yml
The runners are having their labels uniformized across architecture. z15 is being removed in favor of s390x.
Signed-off-by: Manu Bretelle <chantr4@gmail.com>
=> ci: Use `s390x` label to schedule workflows on s390x

scripts/build-fuzzers.sh
to make it less likely for the libbpf fuzz target to run into elfutils bugs that have been fixed upstream since two new fuzz targets were added there back in April.
=> oss-fuzz: bump elfutils

.github/workflows/pahole.yml, .github/workflows/test.yml
Having too new build environment in workflows that build selftests on the host, but run them in a separate QEMU image can lead to problems with runtime linker complaining about missing new enough version of glibc and other dependencies.
Until we update images, fix used Ubuntu version to ubuntu-20.04 to mitigate.
Suggested-by: Manu Bretelle <chantr4@gmail.com>
=> ci: fix Ubuntu version for kernel tests and pahole workflows

ci/diffs/0001-selftests-bpf-Select-CONFIG_FUNCTION_ERROR_INJECTION.patch
Similar to what we did for vmtest [0], libbpf needs the patch setting CONFIG_FUNCTION_ERROR_INJECTION in CI. Add it.
[0] https://github.com/kernel-patches/vmtest/pull/181
=> ci: Add patch setting CONFIG_FUNCTION_ERROR_INJECTION in CI

scripts/sync-kernel.sh
Minor PR to suggest removing that Git version number from the cover letters generated with `git format-patch` when syncing with kernel.
Reference: https://git-scm.com/docs/git-format-patch#Documentation/git-format-patch.txt---no-signatureltsignaturegt
Tested successfully when syncing bpftool (https://github.com/libbpf/bpftool/commit/d10e1e1f89db4d71c9beb4eebcd4d025b3f853de).
=> sync: Remove "git format-patch" signature (version) from cover letter

ci/diffs/0001-s390-define-RUNTIME_DISCARD_EXIT-to-fix-link-error-w.patch
Signed-off-by: Dave Marchevsky <davemarchevsky@fb.com>
=> [patch] backport "s390: define RUNTIME_DISCARD_EXIT to fix link error with GNU ld < 2.36" fix

.github/actions/build-selftests/build_selftests.sh
Currently, CI is unable to locate llvm-16 on
aarch64/gcc, aarch64/llvm-16, and s390x/gcc [0].
This change upgrades the default llvm version to 17.
[0] https://github.com/kernel-patches/bpf/actions/runs/4040302668
Signed-off-by: Joanne Koong <joannekoong@gmail.com>
=> ci: Update default llvm version to 17

include/uapi/linux/openat2.h, scripts/sync-kernel.sh
As reported in [0], we are missing openat2.h in libbpf-local UAPI headers. Sync it and adjust sync script to keep syncing it going forward.
[0] https://github.com/libbpf/libbpf/issues/649
Closes: https://github.com/libbpf/libbpf/issues/649
=> sync: sync include/uapi/linux/openat2.h

.github/actions/build-selftests/build_selftests.sh
Add ability to install specified version of Clang. This replicates what was done in https://github.com/libbpf/ci/pull/86.
=> ci: replicate BPF CI changes for clang installation

.github/actions/build-selftests/build_selftests.sh
LLVM 17 problems were fixed upstream, so switch to using latest v17 in CI.
=> ci: start using llvm-17 now

SYNC.md
When performing a sync with the kernel repository using the `sync-kernel.sh` script, it may be necessary to manually adjust the library's `Makefile` if:
- new source files were added upstream
- new public headers were added upstream
This change adjusts `SYNC.md` to spell out this need.
=> sync: Add section about need for Makefile adjustments

.github/actions/vmtest/action.yml
Seems like deafult branch was renamed s/master/main/, adopt libbpf CI to not fail.
Reported-by: Arnaldo Carvalho de Melo <acme@kernel.org>
=> ci: update libbpf/ci references to use "main"

.gitattributes
We don't need to archive assets/ subdir when packaging libbpf sources in retsnoop and veristat repos. Mark assets/ as export-ignore to skip it.
=> git: add .gitattributes file ignoring assets/ during archiving

ci/diffs/0001-veth-take-into-account-peer-device-for-NETDEV_XDP_AC.patch
Fix test_progs failure xdp_bonding/xdp_bonding_redirect_multi with a missing commit (in bpf, but not in bpf-next yet).
=> ci: Fix test_progs failure

scripts/build-fuzzers.sh
The elfutils project has fixed several issues found by fuzz targets so it should help to prevent the libbpf fuzz target from running into them.
=> fuzz: bump elfutils to 0.189

.gitattributes
As reported by Quentin, using Github Action to archive all submodules (e.g., for retsnoop release packaging) is impacted by it not supporting "<glob>/" pattern in .gitattributes. Use "<glob>/**" instead.
[0] https://github.com/anakryiko/retsnoop/pull/42#issuecomment-1560797837
=> git: make .gitattributes compatible with git-archive-all action

ci/vmtest/run_selftests.sh
This helps troubleshooting by validating what the kconfig of the testing environment is
=> [vmtest] Dump kconfig before running tests

scripts/build-fuzzers.sh
For environments behind proxies, having https:// URL for pulling GIT is more convenient.
=> fuzz: use https-based URL for elfutils

.github/PULL_REQUEST_TEMPLATE.md
This change introduces a pull request template that hopefully helps prevent more libbpf-specific pull requests that should really be submitted to the BPF mailing from being opened against this repository. Recent examples include [0] [1].
[0] https://github.com/libbpf/libbpf/pull/712
[1] https://github.com/libbpf/libbpf/pull/723
=> Introduce pull request template

ci/vmtest/configs/ALLOWLIST-5.5.0, ci/vmtest/configs/DENYLIST-5.5.0
Some tests can't succeed on 5.5, which is very old.
=> ci: update list of tests/subtests for 5.5 kernel

.readthedocs.yaml
Seems like we need to update the config ([0]).
[0] https://blog.readthedocs.com/use-build-os-config/
=> docs: attempt to fix .readthedocs.yaml

.github/workflows/test.yml
Starting recently libbpf CI runs started failing with the following error:
```
##[group]vm_init - Starting virtual machine...
Starting VM with 4 CPUs...
INFO: /dev/kvm exists
KVM acceleration can be used
Could not access KVM kernel module: Permission denied
qemu-system-x86_64: failed to initialize KVM: Permission denied
##[error]Process completed with exit code 2.
```
E.g. see [here](https://github.com/libbpf/libbpf/actions/runs/6819530119/job/18547589967?pr=746). The error happens because CI user has not enough rights to access `/dev/kvm`. On a regular machine the solution would be to add user to group `kvm`, however that would require a re-login, which is cumbersome to achieve in CI setting. Instead, use a recipe described [here](https://stackoverflow.com/questions/37300811/android-studi …
=> ci: give /dev/kvm 0666 permissions inside CI runner

ci/diffs/0001-selftests-bpf-xskxceiver-ksft_print_msg-fix-format-t.patch
Apply fe69a1b1b6ed ("selftests: bpf: xskxceiver: ksft_print_msg: fix format type error") to make bpf-next build.
=> ci: apply temporary patch to make bpf-next build

.github/actions/vmtest/action.yml
Recent kernel commit [0] changed selftests config snippets structure by extracting VM specific options to the file `config.vm`. This file has to be used in `.github/actions/vmtest/action.yml` at step `Prepare to build BPF selftests`, otherwise drivers necessary for e.g. root file system access are not compiled into the kernel, leading to CI failures like [1].
[0] b0cf0dcde8ca ("selftests/bpf: Consolidate VIRTIO/9P configs in config.vm file")
[1] https://github.com/libbpf/libbpf/actions/runs/6830439839/job/18578379328?pr=747
=> ci: use config.vm for kernel config when present

.github/workflows/test.yml
s390 tests are executed on selfhosted runner using root user, avoid setting `/dev/kvm` permissions in such case.
This should fix CI failures like [0].
(Still necessary for x86 tests executed on standard github runners).
[0] https://github.com/libbpf/libbpf/actions/runs/6898545987/job/18768732980?pr=752
Fixes: 168630f852d0 ("ci: give /dev/kvm 0666 permissions inside CI runner")
=> ci: don't set /dev/kvm permissions when CI user is root

ci/vmtest/configs/ALLOWLIST-5.5.0, ci/vmtest/configs/DENYLIST-5.5.0, ci/vmtest/configs/DENYLIST-latest
This test started to fail on LATEST kernel, e.g. see [0]. There are no apparent issues with it on main kernel CI. Link [1] has some details. Overall, it looks like perf event expected by sub-test test_find_vma_pe() of
prog_tests/find_vma.c is never delivered.
[0] https://github.com/libbpf/libbpf/actions/runs/6904382140/job/18784917164
[1] https://github.com/libbpf/libbpf/issues/754
=> ci: disable selftests failing on LATEST and 5.5 kernels

ci/diffs/0001-bpf-patch-out-BPF_F_TEST_REG_INVARIANTS-for-old-kern.patch
Without needing to modify tons of BPF selftests file, make sure we don't pass BPF_F_TEST_REG_INVARIANTS to kernel, to make BPF selftests work on 4.9 and 5.5 kernels.
Also undo previously denylisted tests, assumed to be due to perf events.
=> ci: custom patch to patch out BPF_F_TEST_REG_INVARIANTS flag

.github/actions/vmtest/action.yml, .github/workflows/test.yml
The vmtest action is used from by workflows: test, pahole, ondemand. At the same time vmtest action requires valid access rights to /dev/kvm and is the only action that uses it.
This commit moves /dev/kvm permissions setup from test workflow to vmtest action, in order to make sure that setup logic is shared by all workflows that run vmtest.
Should fix CI failures like [1].
[1] https://github.com/libbpf/libbpf/actions/runs/7104762048/job/19340484589
=> ci: move /dev/kvm permissions setup from to actions/vmtest.yml

ci/vmtest/configs/ALLOWLIST-5.5.0
Allowlist test_global_funcs/arg_tag_ctx* tests to validate libbpf's logic for rewriting __arg_ctx globl subprog argument types on kernels that don't natively support __arg_ctx.
=> ci: allowlist arg_tag_ctx tests for validate __arg_ctx fallback logic

.github/actions/vmtest/action.yml
Since https://github.com/libbpf/ci/commit/1bc40aecb32f1e0f0dc2fff87e7c91b4d5fe03c5 arch parameter needs to be passed to `setup-build-env`
=> ci: Pass arch parameter to setup-build-env

include/linux/filter.h
Fix our Github-specific definition of BPF_CALL_REL macro. It was missing the code part.
=> include: fix BPF_CALL_REL definition

ci/diffs/0001-arch-Kconfig-Move-SPECULATION_MITIGATIONS-to-arch-Kc.patch
Upstream is discussing the exact config to ship. In the meanwhile, which would unblock CI.
More discussions here:
https://lore.kernel.org/lkml/20240423045548.1324969-1-song@kernel.org/T/#u
=> ci/diffs: Add temporary fix for mitigation config

.mailmap, scripts/mailmap-update.sh, scripts/sync-kernel.sh
The kernel repository has a .mailmap file to remap author names and email addresses to their desired format in Git logs (for details, see [gitmailmap documentation][0]). Alas, this is only visible for author information when looking at the logs locally, as GitHub [does not support mailmaps][1] at the moment.
This commit adds a .mailmap file for libbpf, automatically generated from the kernel's version. The script to generate the .mailmap is added, too: it works by grepping email addresses from authors in the repository, and collecting all lines ending with this address in the kernel's .mailmap - in other words, all lines where this address is used as a pattern for a remapping.
To keep the .mailmap up-to-date, add a call to the script to sync-kernel.sh.
[0]: …
=> sync: Sync .mailmap entries

scripts/sync-kernel.sh
In commit 4794f18bf468 ("sync: Sync .mailmap entries"), we updated the sync-up script to automatically update libbpf's .mailmap; however, the script would not take care of committing the changes. Let's address this.
The code is copied and adapted from the part where we commit changes to src/bpf_helper_defs.h.
Follow-up to https://github.com/libbpf/libbpf/pull/800#issuecomment-2085813085.
=> sync: Commit .mailmap changes from script when sync-ing repo

.github/workflows/pahole.yml
pahole staging workflow is using the same old VM image as BPF selftests stages. It doesn't have recent enough glibc, so we can't yet switch to newer Ubuntu, unfortunately.
=> ci: revert switching to ubuntu-latest for pahole-staging workflow

src/Makefile
This fixes a race condition that causes build breakages in e.g. netdata (where `$(OBJDIR)` is set to something other than `.`).
=> Makefile: ensure `$(OBJDIR)` is created before writing to it

.github/workflows/test.yml
Migrate builds to use Ubuntu 24.04 runners.
vmtest will need to run on Ubuntu 20.04 rootfs too (see https://github.com/libbpf/ci/pull/136)
=> ci: run test on Ubuntu 24.04

ci/vmtest/run_selftests.sh
Similar to naming convention in BPF selftests.
=> ci: take into account common local DENYLIST/ALLOWLIST

.github/workflows/build.yml, ci/build-in-docker.sh
run-on-arch-action is simply a wrapper around docker. There is no value in using it in libbpf, as it is not complicated to run non-native arch docker images directly on github-hosted runners.
Docker relies on qemu-user-static installed on the system to emulate different architectures.
Recently there were various reports about multi-arch docker builds failing with seemingly random issues, and it appears to boil down to qemu [1]. I stumbled on this problem while updating s390x runners [2] for BPF CI, and setting up more recent version of qemu helped.
This change addresses recent build failures on s390x and ppc64le.
[1] https://github.com/docker/setup-qemu-action/issues/188
[2] https://github.com/kernel-patches/runner/pull/69
[3] https://docs.docker.com/build/buildkit/#getting-started
=> ci: remove dependency on run-on-arch-action

src/Makefile
Detect whether build system has pkg-config tool, and if not, fallback to manually specifying -lelf -lz as dependency.
Closes: https://github.com/libbpf/libbpf/issues/885
=> Makefile: detect pkg-config availability
